apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaejadle-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: jaejadle=ghcr.io/mayne0213/jaejadle
    argocd-image-updater.argoproj.io/jaejadle.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://gitea0213.kro.kr/bluemayne/jaejadle.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: jaejadle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
