apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jaejadle-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: jaejadle-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: jaejadle/prod
        property: DATABASE_URL
    - secretKey: AWS_S3_ENDPOINT
      remoteRef:
        key: jaejadle/prod
        property: AWS_S3_ENDPOINT
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: jaejadle/prod
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: jaejadle/prod
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_S3_BUCKET_NAME
      remoteRef:
        key: jaejadle/prod
        property: AWS_S3_BUCKET_NAME
    - secretKey: AWS_REGION
      remoteRef:
        key: jaejadle/prod
        property: AWS_REGION
    - secretKey: JWT_SECRET
      remoteRef:
        key: jaejadle/prod
        property: JWT_SECRET
    - secretKey: NEXT_PUBLIC_KAKAO_MAP_KEY
      remoteRef:
        key: jaejadle/prod
        property: NEXT_PUBLIC_KAKAO_MAP_KEY
