apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: main-sha-74f3d387a04bd36a3c78ab61879c0bf6eff36d27

patchesStrategicMerge:
  - deployment-patch.yaml
