apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: github.com/Mayne0213/jaejadle
    newTag: main-sha-e05a870730c2ffcef50d46344c7685ef434fbdce

patchesStrategicMerge:
  - deployment-patch.yaml
