apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-c3ad5b258dc7ed3cecd8725e77927e9f59e05bc3

patchesStrategicMerge:
  - deployment-patch.yaml
