apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: main-sha-9d1f0a6b2f4648cc63f0811950445d4c133d3f75

patchesStrategicMerge:
  - deployment-patch.yaml
