apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-ba3adc66101cfa6a42115f5540750e93aa1b60b3

patchesStrategicMerge:
  - deployment-patch.yaml
