apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-49a004c26c34752ef1c42b3bea9e135b0a536aca

patchesStrategicMerge:
  - deployment-patch.yaml
