apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - externalsecret.yaml
  # - sealed-jaejadle-secret.yaml  # Replaced by ExternalSecret

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-05807199d136990ca345b15c123956749f3e9015

patchesStrategicMerge:
  - deployment-patch.yaml
