apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: github.com/Mayne0213/jaejadle
    newTag: main-sha-788a8c647a85ba93a9ec9fb97176746f5433c410

patchesStrategicMerge:
  - deployment-patch.yaml
