apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-d960ff41f809c65494e1e6517e4a7bb243fa9f6f

patchesStrategicMerge:
  - deployment-patch.yaml
