apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: main-sha-de23e423fa0bf14f7e95530241033a0d3613ad37

patchesStrategicMerge:
  - deployment-patch.yaml
