apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: main-sha-6dc6ef1e83c5535aabefeb2ffc0d79d6e0a9dbbf

patchesStrategicMerge:
  - deployment-patch.yaml
