apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-733bd93e321b7a9d726162a554f37d38026becf8

patchesStrategicMerge:
  - deployment-patch.yaml
