apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - externalsecret.yaml
  # - sealed-jaejadle-secret.yaml  # Replaced by ExternalSecret

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-1d5bd175459ff1d467b62567f66458c340cc6b08

patchesStrategicMerge:
  - deployment-patch.yaml
