apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-8158ff824956ba2cf44e583a70d2acb731ae9ef7

patchesStrategicMerge:
  - deployment-patch.yaml
