apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: github.com/Mayne0213/jaejadle
    newTag: main-sha-62d81e0f85352a21c62bdf7fe8c59958ee457b5f

patchesStrategicMerge:
  - deployment-patch.yaml
