apiVersion: v1
kind: ResourceQuota
metadata:
  name: jaejadle-quota
  namespace: jaejadle
spec:
  hard:
    requests.memory: "1536Mi"
    requests.cpu: "900m"
    limits.memory: "3Gi"
    limits.cpu: "1800m"
    pods: "9"
