apiVersion: v1
kind: ResourceQuota
metadata:
  name: jaejadle-quota
  namespace: jaejadle
spec:
  hard:
    requests.memory: "400Mi"
    requests.cpu: "150m"
    limits.memory: "800Mi"
    limits.cpu: "400m"
    pods: "9"
