apiVersion: v1
kind: Secret
metadata:
  name: jaejadle-secret
  namespace: jaejadle
type: Opaque
stringData:
  jwt-secret: "egorlkjhfdgblkhjgrfdJKHG25436879"
  database-url: "mysql://root:root-password-change-me@proxysql.mariadb.svc.cluster.local:6033/JaejadleDB"
  next-public-kakao-map-key: "8188abb966f8b443ece648e0bbdb5354"
  aws-region: "ap-east-2"
  aws-s3-bucket-name: "jaejadle-bucket"
  aws-s3-bucket-url: "https://s3.minio0213.kro.kr"
  aws-s3-endpoint: "https://s3.minio0213.kro.kr"
  aws-access-key-id: "CipXaWugod1EVco0uosY"
  aws-secret-access-key: "xZy996LKZaPdZ05H6hMM5IT1a3jrM13osngjzAeu"