apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jaejadle-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: jaejadle-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: database-url
      remoteRef:
        key: jaejadle/dev
        property: DATABASE_URL
    - secretKey: aws-s3-endpoint
      remoteRef:
        key: jaejadle/dev
        property: AWS_S3_ENDPOINT
    - secretKey: aws-access-key-id
      remoteRef:
        key: jaejadle/dev
        property: AWS_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: jaejadle/dev
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: aws-s3-bucket-name
      remoteRef:
        key: jaejadle/dev
        property: AWS_S3_BUCKET_NAME
    - secretKey: aws-region
      remoteRef:
        key: jaejadle/dev
        property: AWS_REGION
    - secretKey: jwt-secret
      remoteRef:
        key: jaejadle/dev
        property: JWT_SECRET
    - secretKey: code
      remoteRef:
        key: jaejadle/dev
        property: CODE
