apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-7090004bde38b34999b1fd0100148358d63f6fa7

patchesStrategicMerge:
  - deployment-patch.yaml
