apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: develop-sha-f03d3fc7d7eb690161807839a84085e2b0e840ad

patchesStrategicMerge:
  - deployment-patch.yaml
