apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정 (dev 브랜치 사용 시)
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-63c0b133fead118721144584d226237d003f5d1d

patchesStrategicMerge:
  - deployment-patch.yaml
