apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-ab1c9907ef7a57c2b670a568b5fd7ee80aec4db6

patchesStrategicMerge:
  - deployment-patch.yaml
