apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-a4f74cd5e0b57eed2b206a9d77ea776da70228ef

patchesStrategicMerge:
  - deployment-patch.yaml
