apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-07d3746330413fa5fd1814062f6490883478515e

patchesStrategicMerge:
  - deployment-patch.yaml
