apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: github.com/Mayne0213/jaejadle
    newTag: develop-sha-e4ec90552931228f9c49aa1cc460cf562eeaeb3d

patchesStrategicMerge:
  - deployment-patch.yaml
