apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-ec6ebd7ed988383b61d124b6b4e16c86490e0526

patchesStrategicMerge:
  - deployment-patch.yaml
