apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-7e6fb0e3be39d93ca5d0be57cb0b899c91f4447b

patchesStrategicMerge:
  - deployment-patch.yaml
