apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: develop-sha-140ae0be91428a0b29984cf1f3b4fb97317ce407

patchesStrategicMerge:
  - deployment-patch.yaml
