apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: develop-sha-c2d45de8649b20bb910ba7b249447fa5c2b781f1

patchesStrategicMerge:
  - deployment-patch.yaml
