apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-c4443cbfec1406259118558b1b840df73ca0e85f

patchesStrategicMerge:
  - deployment-patch.yaml
