apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-481bf45ad391a03682be7a6801c73af58be929fc

patchesStrategicMerge:
  - deployment-patch.yaml
