apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: develop-sha-51fa336880e43ee91a0088a4a33ce7a7eaa899d0

patchesStrategicMerge:
  - deployment-patch.yaml
