apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - secretstore.yaml
  - externalsecret.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/jaejadle
    newTag: develop-sha-48f39d314fb270fba5f80ad36783758409e5f363

patchesStrategicMerge:
  - deployment-patch.yaml
