apiVersion: v1
kind: ResourceQuota
metadata:
  name: jaejadle-dev-quota
  namespace: jaejadle-dev
spec:
  hard:
    requests.memory: "200Mi"
    requests.cpu: "60m"
    limits.memory: "400Mi"
    pods: "6"
