apiVersion: v1
kind: Secret
metadata:
  name: jaejadle-secret
  namespace: jaejadle-dev
type: Opaque
stringData:
  jwt-secret: "egorlkjhfdgblkhjgrfdJKHG25436879"
  database-url: "mysql://root:dev-root-password@mariadb-dev.mariadb-dev.svc.cluster.local:3306/JaejadleDB"
  next-public-kakao-map-key: "8188abb966f8b443ece648e0bbdb5354"
  aws-region: "ap-east-2"
  aws-s3-bucket-name: "jaejadle-dev-bucket"
  aws-s3-bucket-url: "http://minio.minio.svc.cluster.local:9000"
  aws-s3-endpoint: "http://minio.minio.svc.cluster.local:9000"
  aws-access-key-id: "CipXaWugod1EVco0uosY"
  aws-secret-access-key: "xZy996LKZaPdZ05H6hMM5IT1a3jrM13osngjzAeu"
